"""
watchdog.py — SENTINEL Agent Watchdog
Auto-generated by install_task.bat — do not edit manually.
Keeps telemetry_agent.py running 24/7, restarts it if it crashes or is closed.
"""
import subprocess
import sys
import time
import pathlib
from datetime import datetime

INSTALL_DIR = pathlib.Path(__file__).resolve().parent
AGENT       = str(INSTALL_DIR / "telemetry_agent.py")
CONFIG      = str(INSTALL_DIR / "config.json")
LOG         = str(INSTALL_DIR / "watchdog.log")
AGENT_LOG   = str(INSTALL_DIR / "agent.log")

# Python path is set by the installer — falls back to current interpreter
PYTHON_PATH_FILE = INSTALL_DIR / "pythonw_path.txt"
if PYTHON_PATH_FILE.exists():
    PYTHON = PYTHON_PATH_FILE.read_text().strip()
else:
    PYTHON = sys.executable


def log(msg):
    line = f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} {msg}"
    try:
        with open(LOG, "a", encoding="utf-8") as f:
            f.write(line + "\n")
    except Exception:
        pass
    print(line)


log("=" * 50)
log("Watchdog started")
log(f"Agent:  {AGENT}")
log(f"Config: {CONFIG}")
log(f"Python: {PYTHON}")
log("=" * 50)

delay = 5

while True:
    try:
        log("Starting agent...")

        si = subprocess.STARTUPINFO()
        si.dwFlags    |= subprocess.STARTF_USESHOWWINDOW
        si.wShowWindow = 0

        with open(AGENT_LOG, "a", encoding="utf-8") as agent_log_f:
            proc = subprocess.Popen(
                [PYTHON, AGENT, "--config", CONFIG],
                startupinfo=si,
                creationflags=subprocess.CREATE_NO_WINDOW,
                stdout=agent_log_f,
                stderr=subprocess.STDOUT,
            )

        log(f"Agent running — PID {proc.pid}")
        proc.wait()
        log(f"Agent exited with code {proc.returncode} — restarting in {delay}s")

    except Exception as e:
        log(f"Watchdog error: {e} — restarting in {delay}s")

    time.sleep(delay)
